(deftheme oldlace
  "Created 2014-09-03.")

(custom-theme-set-faces
 'oldlace
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#7b4135"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#949494"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#64502f"))))
 '(font-lock-reference-face ((((class color) (min-colors 89)) (:foreground "#64502f"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#64502f"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#949494"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#714355" :bold t))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold ((class color) (min-colors 89)) :foreground "#3f567b"))))
 '(font-lock-string-face ((t (:foreground "dark green"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#634575"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#3f5b32"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#fa0c0c" :background "#e6dfd1"))))
 '(region ((((class color) (min-colors 89)) (:background "#525252" :foreground "#fdf5e6"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#6b6b6b" :background "#d0c9bd"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#e6dfd1"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#e6dfd1" :foreground "#787878"))))
 '(cursor ((((class color) (min-colors 89)) (:background "#d0c9bd"))))
 '(show-paren-match-face ((((class color) (min-colors 89)) (:background "#fa0c0c"))))
 '(isearch ((((class color) (min-colors 89)) (:bold t :foreground "#fa0c0c" :background "#d0c9bd"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width 1 :color nil :style released-button) :bold t :foreground "#787878" :background "#e6dfd1"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box (:line-width 1 :color nil :style pressed-button) :foreground "#5e5e5e" :background "#fdf5e6"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:bold t :foreground "#5e5e5e" :background nil))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:background "#bab4a9"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#6b6b6b"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:bold t :foreground "#3f567b"))))
 '(default-italic ((((class color) (min-colors 89)) (:italic t))))
 '(link ((((class color) (min-colors 89)) (:foreground "#64502f" :underline t))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#5e5e5e"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#787878"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:bold t :foreground "#5e5e5e" :height 1.1))))
 '(org-level-2 ((((class color) (min-colors 89)) (:bold nil :foreground "#6b6b6b"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:bold t :foreground "#787878"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:bold nil :foreground "#bab4a9"))))
 '(org-date ((((class color) (min-colors 89)) (:underline t :foreground "#3f5b32"))))
 '(org-footnote ((((class color) (min-colors 89)) (:underline t :foreground "#787878"))))
 '(org-link ((((class color) (min-colors 89)) (:underline t :foreground "#634575"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#714355"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#6b6b6b"))))
 '(org-quote ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-verse ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-todo ((((class color) (min-colors 89)) :foreground "#3f567b" :bold t)))
 '(org-done ((((class color) (min-colors 89)) (:bold t :foreground "#bab4a9"))))
 '(org-warning ((((class color) (min-colors 89)) (:underline t :foreground "#fa0c0c"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:weight bold :foreground "#6b6b6b" :box (:color "#787878") :background "#d0c9bd"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#3f5b32" :height 1.1))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:weight normal :foreground "#787878"))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:weight bold :foreground "#3f567b" :height 1.4))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#634575"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#7b4135"))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#787878"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#714355"))))
 '(font-latex-bold-face ((((class color) (min-colors 89)) (:foreground "#634575"))))
 '(font-latex-italic-face ((((class color) (min-colors 89)) (:foreground "#394d6d" :italic t))))
 '(font-latex-string-face ((((class color) (min-colors 89)) (:foreground "#305f5e"))))
 '(font-latex-match-reference-keywords ((((class color) (min-colors 89)) (:foreground "#64502f"))))
 '(font-latex-match-variable-keywords ((((class color) (min-colors 89)) (:foreground "#3f5b32"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#fa0c0c"))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#787878"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#3f567b" :bold t))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:foreground "#3f567b"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:foreground "#3f5b32"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "#634575"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "#714355" :bold t))))
 '(mu4e-view-url-number-face ((((class color) (min-colors 89)) (:foreground "#634575"))))
 '(mu4e-cited-1-face ((((class color) (min-colors 89)) (:foreground "#5e5e5e"))))
 '(mu4e-cited-7-face ((((class color) (min-colors 89)) (:foreground "#6b6b6b"))))
 '(mu4e-header-marks-face ((((class color) (min-colors 89)) (:foreground "#634575"))))
 '(ffap ((((class color) (min-colors 89)) (:foreground "#787878"))))
 '(js2-private-function-call ((((class color) (min-colors 89)) (:foreground "#64502f"))))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 89)) (:foreground "#305f5e"))))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 89)) (:foreground "#546789"))))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#64502f"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#fa0c0c"))))
 '(ac-completion-face ((((class color) (min-colors 89)) (:underline t :foreground "#3f567b"))))
 '(info-quoted-name ((((class color) (min-colors 89)) (:foreground "#7b4135"))))
 '(info-string ((((class color) (min-colors 89)) (:foreground "#305f5e"))))
 '(icompletep-determined ((((class color) (min-colors 89)) :foreground "#7b4135")))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) :foreground "#7b4135")))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) :foreground "#5e5e5e")))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) :foreground "#3f5b32")))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) :foreground "#634575")))
 '(slime-repl-inputed-output-face ((((class color) (min-colors 89)) (:foreground "#634575"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) :foreground nil :background "#fa0c0c")))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) :foreground "#525252")))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) :foreground "#634575")))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) :foreground "#3f5b32")))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) :foreground "#64502f")))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) :foreground "#3f567b")))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) :foreground "#525252")))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) :foreground "#634575")))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) :foreground "#3f5b32")))
 '(magit-item-highlight ((((class color) (min-colors 89)) :background "#d0c9bd")))
 '(magit-section-heading ((((class color) (min-colors 89)) (:foreground "#3f567b" :weight bold))))
 '(magit-hunk-heading ((((class color) (min-colors 89)) (:background "#d0c9bd"))))
 '(magit-section-highlight ((((class color) (min-colors 89)) (:background "#e6dfd1"))))
 '(magit-hunk-heading-highlight ((((class color) (min-colors 89)) (:background "#d0c9bd"))))
 '(magit-diff-context-highlight ((((class color) (min-colors 89)) (:background "#d0c9bd" :foreground "#6b6b6b"))))
 '(magit-diffstat-added ((((class color) (min-colors 89)) (:foreground "#634575"))))
 '(magit-diffstat-removed ((((class color) (min-colors 89)) (:foreground "#3f5b32"))))
 '(magit-process-ok ((((class color) (min-colors 89)) (:foreground "#714355" :weight bold))))
 '(magit-process-ng ((((class color) (min-colors 89)) (:foreground "#fa0c0c" :weight bold))))
 '(magit-branch ((((class color) (min-colors 89)) (:foreground "#64502f" :weight bold))))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#6b6b6b"))))
 '(magit-hash ((((class color) (min-colors 89)) (:foreground "#5e5e5e"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) :foreground "#fa0c0c")))
 '(default ((((class color) (min-colors 89)) (:background "#fdf5e6" :foreground "#525252")))))

(provide-theme 'oldlace)
