(deftheme sanityinc-tomorrow-night
  "Created 2014-09-03.")

;; use 'helm-colors to find out faces available for say 'dired 'helm etc
;; I think faces defined in `dired+' start with 'diredp-

(custom-theme-set-variables
 'sanityinc-tomorrow-night
 '(ansi-color-names-vector ["#c5c8c6" "#cc6666" "SeaGreen" "#f0c674" "#81a2be" "#b294bb" "#8abeb7" "#1d1f21"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'sanityinc-tomorrow-night
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(font-lock-doc-string-face ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 ;; '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#009090" :background "#031316"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#cc6666"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:style wave :color "#cc6666")))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:style wave :color "#de935f")))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#1d1f21" :background "#cc6666"))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#1d1f21" :background "#f0c674"))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#1d1f21" :background "#de935f"))))
 '(flymake-warnline ((((class color) (min-colors 89)) (:underline (:style wave :color "#de935f") :background "#1d1f21"))))
 '(flymake-errline ((((class color) (min-colors 89)) (:underline (:style wave :color "#cc6666") :background "#1d1f21"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#c5c8c6"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#c5c8c6"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(match ((((class color) (min-colors 89)) (:foreground "#81a2be" :background "#1d1f21" :inverse-video t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#f0c674" :background "#1d1f21" :inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#8abeb7" :background "#1d1f21" :inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#1d1f21" :inherit font-lock-warning-face :inverse-video t))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(anzu-replace-highlight ((((class color) (min-colors 89)) (:inherit isearch-lazy-highlight-face))))
 '(anzu-replace-to ((((class color) (min-colors 89)) (:inherit isearch))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "#cc6666" :background "#1d1f21"))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#f0c674" :weight bold :underline nil))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#7f9f7f" :background nil :height 100))))
 '(cursor ((((class color) (min-colors 89)) (:background "#cc6666"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#161616"))))
 '(linum ((((class color) (min-colors 89)) (:background "#373b41" :foreground "#b5bd68" :italic nil))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#FFFFFF"))))
 '(border ((((class color) (min-colors 89)) (:background "#373b41" :foreground "#373b41"))))
 '(border-glyph ((((class color) (min-colors 89)) (nil))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#282a2e"))))
 '(gui-element ((((class color) (min-colors 89)) (:background "#373b41" :foreground "#c5c8c6"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(region ((((class color) (min-colors 89)) (:background "#8F621D" :inverse-video nil))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#282a2e"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#b294bbn" :background nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#cc6666" :foreground "#f0c674"))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:foreground "#cc6666" :background "#f0c674"))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:background "#373b41" :foreground "#969896"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background "#373b41" :foreground "#969896"))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background "#373b41" :foreground "#cc6666"))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background "#373b41" :foreground "#969896"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background "#373b41" :foreground "#969896"))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:background "#373b41" :foreground "#f0c674"))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:background "#373b41" :foreground "#cc6666"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background "#373b41" :foreground "#969896"))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:background "#373b41" :foreground "#cc6666"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#b294bb" :foreground "#1d1f21"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "#cc6666" :foreground "#1d1f21"))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-match))))
 '(sp-show-pair-mismatch-face ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-mismatch))))
 '(paren-face-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-match))))
 '(paren-face-mismatch ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-mismatch))))
 '(paren-face-no-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-mismatch))))
 '(paren-face ((((class color) (min-colors 89)) (:foreground "#969896" :background nil))))
 '(sh-heredoc ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-string-face :weight normal))))
 '(sh-quoted-exec ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-preprocessor-face))))
 '(slime-highlight-edits-face ((((class color) (min-colors 89)) (:weight bold))))
 '(slime-repl-input-face ((((class color) (min-colors 89)) (:weight normal :underline nil))))
 '(slime-repl-prompt-face ((((class color) (min-colors 89)) (:underline nil :weight bold :foreground "#b294bb"))))
 '(slime-repl-result-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(slime-repl-output-face ((((class color) (min-colors 89)) (:foreground "#81a2be" :background "#1d1f21"))))
 '(csv-separator-face ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#8abeb7" :background nil))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#81a2be" :background nil))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:inherit diff-added :inverse-video t))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:inherit diff-removed :inverse-video t))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:background "#b5bd68"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:background "#81a2be"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:background "#de935f"))))
 '(diff-hl-unknown ((((class color) (min-colors 89)) :background "#b294bb")))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:foreground nil :background nil :inverse-video t))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:foreground nil :background nil :inverse-video t))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:foreground "#969896" :background nil :inverse-video t))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:foreground "#969896" :background nil :inverse-video t))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#b5bd68" :weight bold))))
 '(macrostep-expansion-highlight-face ((((class color) (min-colors 89)) (:inherit highlight :foreground nil))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#c5c8c6"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#b5bd68" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#81a2be" :weight normal))))
 '(diredp-directory ((((class color) (min-colors 89)) (:foreground "#81a2be" :weight normal))))
 '(dired-file-name ((((class color) (min-colors 89)) (:foreground "#D7b78f" :weight normal))))
 '(diredp-file-name ((((class color) (min-colors 89)) (:foreground "#D7b78f" :weight normal))))
 '(diredp-compressed-file-suffix ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(diredp-deletion ((((class color) (min-colors 89)) (:inherit error :inverse-video t))))
 '(diredp-deletion-file-name ((((class color) (min-colors 89)) (:inherit error))))
 '(diredp-dir-heading ((((class color) (min-colors 89)) (:foreground "#81a2be" :weight bold :underline t))))
 '(diredp-dir-priv ((((class color) (min-colors 89)) (:foreground "#81a2be" :background nil :weight normal))))
 '(diredp-exec-priv ((((class color) (min-colors 89)) (:foreground "#81a2be" :background nil))))
 '(diredp-executable-tag ((((class color) (min-colors 89)) (:foreground "#cc6666" :background nil))))
 '(diredp-file-suffix ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(diredp-flag-mark ((((class color) (min-colors 89)) (:foreground "#b5bd68" :inverse-video t))))
 '(diredp-flag-mark-line ((((class color) (min-colors 89)) (:background nil :inherit highlight))))
 '(diredp-ignored-file-name ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(diredp-link-priv ((((class color) (min-colors 89)) (:background nil :foreground "#b294bb"))))
 '(diredp-mode-line-flagged ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(diredp-mode-line-marked ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(diredp-no-priv ((((class color) (min-colors 89)) (:background nil))))
 '(diredp-number ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(diredp-other-priv ((((class color) (min-colors 89)) (:background nil :foreground "#b294bb"))))
 '(diredp-rare-priv ((((class color) (min-colors 89)) (:foreground "#cc6666" :background nil))))
 '(diredp-read-priv ((((class color) (min-colors 89)) (:foreground "#b5bd68" :background nil))))
 '(diredp-symlink ((((class color) (min-colors 89)) (:foreground "#de935f" ))))
 '(diredp-write-priv ((((class color) (min-colors 89)) (:foreground "#f0c674" :background nil))))
 '(magit-branch ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(magit-header ((((class color) (min-colors 89)) (:inherit nil :weight bold))))
 '(magit-item-highlight ((((class color) (min-colors 89)) (:inherit highlight :background nil))))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(magit-log-graph ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(magit-log-sha1 ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(magit-log-head-label-bisect-bad ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(magit-log-head-label-bisect-good ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(magit-log-head-label-default ((((class color) (min-colors 89)) (:foreground "#f0c674" :box nil :weight bold))))
 '(magit-log-head-label-head ((((class color) (min-colors 89)) (:foreground "#de935f" :box nil :weight bold))))
 '(magit-log-head-label-local ((((class color) (min-colors 89)) (:foreground "#b294bb" :box nil :weight bold))))
 '(magit-log-head-label-remote ((((class color) (min-colors 89)) (:foreground "#b294bb" :box nil :weight bold))))
 '(magit-log-head-label-tags ((((class color) (min-colors 89)) (:foreground "#8abeb7" :box nil :weight bold))))
 '(magit-log-head-label-wip ((((class color) (min-colors 89)) (:foreground "#81a2be" :box nil :weight bold))))
 '(magit-process-ok ((((class color) (min-colors 89)) (:inherit success))))
 '(magit-process-ng ((((class color) (min-colors 89)) (:inherit error))))
 '(magit-section-title ((((class color) (min-colors 89)) (:foreground "#81a2be" :weight bold))))
 '(git-gutter:modified ((((class color) (min-colors 89)) (:foreground "#b294bb" :weight bold))))
 '(git-gutter:added ((((class color) (min-colors 89)) (:foreground "#b5bd68" :weight bold))))
 '(git-gutter:deleted ((((class color) (min-colors 89)) (:foreground "#cc6666" :weight bold))))
 '(git-gutter:unchanged ((((class color) (min-colors 89)) (:background "#f0c674"))))
 '(git-gutter-fr:modified ((((class color) (min-colors 89)) (:foreground "#b294bb" :weight bold))))
 '(git-gutter-fr:added ((((class color) (min-colors 89)) (:foreground "#b5bd68" :weight bold))))
 '(git-gutter-fr:deleted ((((class color) (min-colors 89)) (:foreground "#cc6666" :weight bold))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#373b41" :box (:line-width 1 :color "#c5c8c6")))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(compilation-message-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(grep-context-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(grep-error-face ((((class color) (min-colors 89)) (:foreground "#cc6666" :weight bold :underline t))))
 '(grep-hit-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(grep-match-face ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit match))))
 '(regex-tool-matched-face ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit match))))
 '(mm/master-face ((((class color) (min-colors 89)) (:inherit region :foreground nil :background nil))))
 '(mm/mirror-face ((((class color) (min-colors 89)) (:inherit region :foreground nil :background nil))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:inherit warning))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:inherit diredp-dir-priv))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:inherit diredp-file-name))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:inherit diredp-symlink))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:inherit diredp-executable-tag))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "SkyBlue" :background nil))))
 '(helm-helper ((((class color) (min-colors 89)) (:background "#151515"))))
 '(helm-header ((((class color) (min-colors 89)) (:background "#151515"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 ;; '(helm-selection ((((class color) (min-colors 89)) (:inherit highlight))))
 '(helm-selection ((((class color) (min-colors 89))
                    (:inherit highlight :background "#373b41" :underline nil))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:inherit org-document-title))))

 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#81a2be" :underline nil))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#373b41"))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit org-column :weight bold :underline t))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#81a2be" :underline t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(org-document-title ((((class color) (min-colors 89)) (:weight bold :foreground "#de935f" :height 1.44))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#1d1f21" :background "#1d1f21"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#81a2be" :underline t))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "#cc6666"))))
 '(markdown-url-face ((((class color) (min-colors 89)) (:inherit link))))
 '(markdown-link-face ((((class color) (min-colors 89)) (:foreground "#81a2be" :underline t))))
 '(hl-sexp-face ((((class color) (min-colors 89)) (:background "#373b41"))))
 '(highlight-symbol-face ((((class color) (min-colors 89)) (:background "#373b41" :weight bold))))
 '(highlight-80+ ((((class color) (min-colors 89)) (:background "#373b41"))))
 '(py-builtins-face ((((class color) (min-colors 89)) (:foreground "#de935f" :weight normal))))
 '(js2-warning ((((class color) (min-colors 89)) (:underline "#de935f"))))
 '(js2-error ((((class color) (min-colors 89)) (:foreground nil :underline "#cc6666"))))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 ;; '(js2-function-param ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(js2-function-param ((((class color) (min-colors 89)) (:foreground "SeaGreen"))))
 '(js2-instance-member ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(js2-private-function-call ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(js3-warning-face ((((class color) (min-colors 89)) (:underline "#de935f"))))
 '(js3-error-face ((((class color) (min-colors 89)) (:foreground nil :underline "#cc6666"))))
 '(js3-external-variable-face ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(js3-function-param-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(js3-jsdoc-tag-face ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(js3-jsdoc-type-face ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(js3-jsdoc-value-face ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(js3-jsdoc-html-tag-name-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(js3-jsdoc-html-tag-delimiter-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(js3-instance-member-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(js3-private-function-call-face ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(coffee-mode-class-name ((((class color) (min-colors 89)) (:foreground "#de935f" :weight bold))))
 '(coffee-mode-function-param ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(nxml-name-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-constant-face))))
 '(nxml-attribute-local-name-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-variable-name-face))))
 '(nxml-ref-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-preprocessor-face))))
 '(nxml-delimiter-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-keyword-face))))
 '(nxml-delimited-data-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-string-face))))
 '(rng-error-face ((((class color) (min-colors 89)) (:underline "#cc6666"))))
 '(erb-delim-face ((((class color) (min-colors 89)) (:background "#373b41"))))
 '(erb-exec-face ((((class color) (min-colors 89)) (:background "#373b41" :weight bold))))
 '(erb-exec-delim-face ((((class color) (min-colors 89)) (:background "#373b41"))))
 '(erb-out-face ((((class color) (min-colors 89)) (:background "#373b41" :weight bold))))
 '(erb-out-delim-face ((((class color) (min-colors 89)) (:background "#373b41"))))
 '(erb-comment-face ((((class color) (min-colors 89)) (:background "#373b41" :weight bold :slant italic))))
 '(erb-comment-delim-face ((((class color) (min-colors 89)) (:background "#373b41"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground nil :background nil :weight normal))))
 '(message-header-subject ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#f0c674"))))
 '(message-header-to ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#de935f"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:inherit message-header-to :foreground nil))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#81a2be" :background nil))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#8abeb7" :background nil :slant normal))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(jabber-chat-prompt-local ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(jabber-chat-prompt-foreign ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(jabber-chat-prompt-system ((((class color) (min-colors 89)) (:foreground "#f0c674" :weight bold))))
 '(jabber-chat-text-local ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(jabber-chat-text-foreign ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(jabber-chat-text-error ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(jabber-roster-user-online ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(jabber-roster-user-xa ((((class color) (min-colors 89)) :foreground "#969896")))
 '(jabber-roster-user-dnd ((((class color) (min-colors 89)) :foreground "#f0c674")))
 '(jabber-roster-user-away ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(jabber-roster-user-chatty ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(jabber-roster-user-error ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(jabber-roster-user-offline ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(jabber-rare-time-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(jabber-activity-face ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(jabber-activity-personal-face ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:foreground "#c5c8c6" :background "#282a2e"))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:foreground "#c5c8c6" :background "#373b41"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit nil :foreground "#81a2be"))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit nil :foreground "#b294bb"))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit nil :foreground "#c5c8c6"))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit nil :foreground "#8abeb7"))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit nil :foreground "#de935f"))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit nil :foreground "#81a2be"))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit nil :foreground "#b294bb"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit nil :foreground "#c5c8c6"))))
 '(outline-9 ((((class color) (min-colors 89)) (:inherit nil :foreground "#8abeb7"))))
 '(ledger-font-comment-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(ledger-font-occur-narrowed-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face :invisible t))))
 '(ledger-font-occur-xact-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(ledger-font-payee-cleared-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(ledger-font-payee-uncleared-face ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(ledger-font-posting-account-cleared-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(ledger-font-posting-account-face ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(ledger-font-posting-account-pending-face ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(ledger-font-xact-highlight-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(ledger-occur-narrowed-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face :invisible t))))
 '(ledger-occur-xact-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(mu4e-header-highlight-face ((((class color) (min-colors 89)) (:underline nil :inherit region))))
 '(mu4e-header-marks-face ((((class color) (min-colors 89)) (:underline nil :foreground "#f0c674"))))
 '(mu4e-flagged-face ((((class color) (min-colors 89)) (:foreground "#de935f" :inherit nil))))
 '(mu4e-replied-face ((((class color) (min-colors 89)) (:foreground "#81a2be" :inherit nil))))
 '(mu4e-unread-face ((((class color) (min-colors 89)) (:foreground "#f0c674" :inherit nil))))
 '(mu4e-cited-1-face ((((class color) (min-colors 89)) (:inherit outline-1 :slant normal))))
 '(mu4e-cited-2-face ((((class color) (min-colors 89)) (:inherit outline-2 :slant normal))))
 '(mu4e-cited-3-face ((((class color) (min-colors 89)) (:inherit outline-3 :slant normal))))
 '(mu4e-cited-4-face ((((class color) (min-colors 89)) (:inherit outline-4 :slant normal))))
 '(mu4e-cited-5-face ((((class color) (min-colors 89)) (:inherit outline-5 :slant normal))))
 '(mu4e-cited-6-face ((((class color) (min-colors 89)) (:inherit outline-6 :slant normal))))
 '(mu4e-cited-7-face ((((class color) (min-colors 89)) (:inherit outline-7 :slant normal))))
 '(mu4e-ok-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(mu4e-view-contact-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#f0c674"))))
 '(mu4e-view-link-face ((((class color) (min-colors 89)) (:inherit link :foreground "#81a2be"))))
 '(mu4e-view-url-number-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#8abeb7"))))
 '(mu4e-view-attach-number-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#de935f"))))
 '(mu4e-highlight-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(mu4e-title-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#b5bd68"))))
 '(gnus-cite-1 ((((class color) (min-colors 89)) (:inherit outline-1 :foreground nil))))
 '(gnus-cite-2 ((((class color) (min-colors 89)) (:inherit outline-2 :foreground nil))))
 '(gnus-cite-3 ((((class color) (min-colors 89)) (:inherit outline-3 :foreground nil))))
 '(gnus-cite-4 ((((class color) (min-colors 89)) (:inherit outline-4 :foreground nil))))
 '(gnus-cite-5 ((((class color) (min-colors 89)) (:inherit outline-5 :foreground nil))))
 '(gnus-cite-6 ((((class color) (min-colors 89)) (:inherit outline-6 :foreground nil))))
 '(gnus-cite-7 ((((class color) (min-colors 89)) (:inherit outline-7 :foreground nil))))
 '(gnus-cite-8 ((((class color) (min-colors 89)) (:inherit outline-8 :foreground nil))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:inherit message-header-other))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:inherit message-header-subject))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:inherit message-header-other-face :weight bold :foreground "#de935f"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:inherit message-header-name))))
 '(gnus-button ((((class color) (min-colors 89)) (:inherit link :foreground nil))))
 '(gnus-signature ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 89)) (:foreground "#81a2be" :weight normal))))
 '(gnus-summary-normal-read ((((class color) (min-colors 89)) (:foreground "#c5c8c6" :weight normal))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 89)) (:foreground "#8abeb7" :weight normal))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 89)) (:foreground "#de935f" :weight normal))))
 '(gnus-summary-low-unread ((((class color) (min-colors 89)) (:foreground "#969896" :weight normal))))
 '(gnus-summary-low-read ((((class color) (min-colors 89)) (:foreground "#969896" :weight normal))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 89)) (:foreground "#969896" :weight normal))))
 '(gnus-summary-high-unread ((((class color) (min-colors 89)) (:foreground "#f0c674" :weight normal))))
 '(gnus-summary-high-read ((((class color) (min-colors 89)) (:foreground "#b5bd68" :weight normal))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 89)) (:foreground "#b5bd68" :weight normal))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 89)) (:foreground "#de935f" :weight normal))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:foreground "#cc6666" :background nil :weight normal))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-1))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-2))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-3))))
 '(gnus-group-mail-4 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-4))))
 '(gnus-group-mail-5 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-5))))
 '(gnus-group-mail-6 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-6))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-1 :foreground "#969896"))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-2 :foreground "#969896"))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-3 :foreground "#969896"))))
 '(gnus-group-mail-4-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-4 :foreground "#969896"))))
 '(gnus-group-mail-5-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-5 :foreground "#969896"))))
 '(gnus-group-mail-6-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-6 :foreground "#969896"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-5))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-6))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-7))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-8))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-1))))
 '(gnus-group-news-6 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-2))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-1 :foreground "#969896"))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-2 :foreground "#969896"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-3 :foreground "#969896"))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-4 :foreground "#969896"))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-5 :foreground "#969896"))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-6 :foreground "#969896"))))
 '(erc-direct-msg-face ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(erc-error-face ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(erc-header-face ((((class color) (min-colors 89)) (:foreground "#c5c8c6" :background "#282a2e"))))
 '(erc-input-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(erc-current-nick-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(erc-my-nick-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(erc-nick-default-face ((((class color) (min-colors 89)) (:weight normal :foreground "#b294bb"))))
 '(erc-nick-msg-face ((((class color) (min-colors 89)) (:weight normal :foreground "#f0c674"))))
 '(erc-notice-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(erc-pal-face ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(erc-prompt-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(erc-timestamp-face ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(erc-keyword-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(twittering-username-face ((((class color) (min-colors 89)) (:inherit erc-pal-face))))
 '(twittering-uri-face ((((class color) (min-colors 89)) (:foreground "#81a2be" :inherit link))))
 '(twittering-timeline-header-face ((((class color) (min-colors 89)) (:foreground "#b5bd68" :weight bold))))
 '(twittering-timeline-footer-face ((((class color) (min-colors 89)) (:inherit twittering-timeline-header-face))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(term ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit default))))
 '(term-color-black ((((class color) (min-colors 89)) (:foreground "#c5c8c6" :background "#c5c8c6"))))
 '(term-color-red ((((class color) (min-colors 89)) (:foreground "#cc6666" :background "#cc6666"))))
 '(term-color-green ((((class color) (min-colors 89)) (:foreground "#b5bd68" :background "#b5bd68"))))
 '(term-color-yellow ((((class color) (min-colors 89)) (:foreground "#f0c674" :background "#f0c674"))))
 '(term-color-blue ((((class color) (min-colors 89)) (:foreground "#81a2be" :background "#81a2be"))))
 '(term-color-magenta ((((class color) (min-colors 89)) (:foreground "#b294bb" :background "#b294bb"))))
 '(term-color-cyan ((((class color) (min-colors 89)) (:foreground "#8abeb7" :background "#8abeb7"))))
 '(term-color-white ((((class color) (min-colors 89)) (:foreground "#1d1f21" :background "#1d1f21"))))
 '(default ((((class color) (min-colors 89)) (:inherit default :foreground "#D7b78f" :background "#161616"))))
 '(hl-line ((t (:inherit highlight :background "#373b41" :underline nil))))

 ;; --- My custom ---
 '(persp-selected-face ((((class color) (min-colors 89)) (:weight normal :height 100 :foreground "#81a2be"))))
 '(projectile-selected-face ((((class color) (min-colors 89)) (:inherit persp-selected-face))))
 '(mode-line
   ((((class color) (min-colors 89))
     (:foreground nil
      :background "#373b41"
      :weight normal
      :box (:line-width 1 :color "#969896") :height 115))))
 '(mode-line-inactive
   ((((class color) (min-colors 89))
     (:inherit mode-line
      :foreground "#969896"
      :background "#373b41"
      :weight normal
      :box (:line-width 1 :color "#373b41")))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#eab700" :background nil :weight bold))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#c5c8c6" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#b294bb" :box nil :weight bold))))
 '(mode-line-read-only-face ((t (:foreground "#4271ae"))))
 '(mode-line-modified-face ((t (:foreground "#c82829" :background "#ffffff"))))
 '(mode-line-unmodified-face ((t (:foreground "#969896"))))
 '(mode-line-folder-face ((t (:height 100))))
 '(mode-line-position-face ((t (:foreground "#969896" :height 95))))
 '(mode-line-80col-face ((t (:foreground "black" :background "#eab700"))))

 ;; better diff color?
 '(diff-refine-change ((t (:background "#aaaa22" :foreground "black"))))
 )

(provide-theme 'sanityinc-tomorrow-night)
